// SPDX-FileCopyrightText: 2002-2026 PCSX2 Dev Team
// SPDX-License-Identifier: GPL-3.0
//
// ARM64 EE Recompiler — Interpreter-fallback stubs for all non-branch opcodes.
// Each rec*() emits a call to the corresponding interpreter function.

#include "Common.h"
#include "R5900OpcodeTables.h"
#include "arm64/arm64Emitter.h"

using namespace R5900;

// Helper macro: emit interpreter call for a standard opcode
#define REC_INTERP(name) \
	void rec##name() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::name); }

// Helper macro: emit interpreter call for an MMI opcode
#define REC_INTERP_MMI(name) \
	void rec##name() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::MMI::name); }

// Helper macro: emit interpreter call for a COP0 opcode
#define REC_INTERP_COP0(name) \
	void rec##name() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP0::name); }

// Helper macro: emit interpreter call for a COP1 opcode
#define REC_INTERP_COP1(name) \
	void rec##name() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP1::name); }

namespace R5900 {
namespace Dynarec {
namespace OpcodeImpl {

// ---- Misc ----
REC_INTERP(Unknown)
REC_INTERP(MMI_Unknown)
REC_INTERP(COP0_Unknown)
REC_INTERP(COP1_Unknown)
REC_INTERP(COP2)
REC_INTERP(CACHE)
REC_INTERP(PREF)
REC_INTERP(SYNC)

// ---- Traps ----
REC_INTERP(TGEI)
REC_INTERP(TGEIU)
REC_INTERP(TLTI)
REC_INTERP(TLTIU)
REC_INTERP(TEQI)
REC_INTERP(TNEI)
REC_INTERP(TGE)
REC_INTERP(TGEU)
REC_INTERP(TLT)
REC_INTERP(TLTU)
REC_INTERP(TEQ)
REC_INTERP(TNE)

// ---- Arithmetic ----
REC_INTERP(MULT)
REC_INTERP(MULTU)
REC_INTERP(MULT1)
REC_INTERP(MULTU1)
REC_INTERP(MADD)
REC_INTERP(MADDU)
REC_INTERP(MADD1)
REC_INTERP(MADDU1)
REC_INTERP(DIV)
REC_INTERP(DIVU)
REC_INTERP(DIV1)
REC_INTERP(DIVU1)

REC_INTERP(ADDI)
REC_INTERP(ADDIU)
REC_INTERP(DADDI)
REC_INTERP(DADDIU)
REC_INTERP(DADD)
REC_INTERP(DADDU)
REC_INTERP(DSUB)
REC_INTERP(DSUBU)
REC_INTERP(ADD)
REC_INTERP(ADDU)
REC_INTERP(SUB)
REC_INTERP(SUBU)

REC_INTERP(ANDI)
REC_INTERP(ORI)
REC_INTERP(XORI)
REC_INTERP(AND)
REC_INTERP(OR)
REC_INTERP(XOR)
REC_INTERP(NOR)
REC_INTERP(SLTI)
REC_INTERP(SLTIU)
REC_INTERP(SLT)
REC_INTERP(SLTU)
REC_INTERP(LUI)

// ---- Shifts ----
REC_INTERP(SLL)
REC_INTERP(SRL)
REC_INTERP(SRA)
REC_INTERP(SLLV)
REC_INTERP(SRLV)
REC_INTERP(SRAV)
REC_INTERP(DSLLV)
REC_INTERP(DSRLV)
REC_INTERP(DSRAV)
REC_INTERP(DSLL)
REC_INTERP(DSRL)
REC_INTERP(DSRA)
REC_INTERP(DSLL32)
REC_INTERP(DSRL32)
REC_INTERP(DSRA32)

// ---- Moves ----
REC_INTERP(MOVZ)
REC_INTERP(MOVN)
REC_INTERP(MFHI)
REC_INTERP(MTHI)
REC_INTERP(MFLO)
REC_INTERP(MTLO)
REC_INTERP(MFSA)
REC_INTERP(MTSA)
REC_INTERP(MTSAB)
REC_INTERP(MTSAH)
REC_INTERP(MFHI1)
REC_INTERP(MTHI1)
REC_INTERP(MFLO1)
REC_INTERP(MTLO1)

// ---- Loads ----
REC_INTERP(LDL)
REC_INTERP(LDR)
REC_INTERP(LQ)
REC_INTERP(LB)
REC_INTERP(LH)
REC_INTERP(LWL)
REC_INTERP(LW)
REC_INTERP(LBU)
REC_INTERP(LHU)
REC_INTERP(LWR)
REC_INTERP(LWU)
REC_INTERP(LWC1)
REC_INTERP(LQC2)
REC_INTERP(LD)

// ---- Stores ----
REC_INTERP(SQ)
REC_INTERP(SB)
REC_INTERP(SH)
REC_INTERP(SWL)
REC_INTERP(SW)
REC_INTERP(SDL)
REC_INTERP(SDR)
REC_INTERP(SWR)
REC_INTERP(SWC1)
REC_INTERP(SQC2)
REC_INTERP(SD)

// ---- MMI ----
namespace MMI {

REC_INTERP_MMI(PLZCW)
REC_INTERP_MMI(PMFHL)
REC_INTERP_MMI(PMTHL)
REC_INTERP_MMI(PSLLH)
REC_INTERP_MMI(PSRLH)
REC_INTERP_MMI(PSRAH)
REC_INTERP_MMI(PSLLW)
REC_INTERP_MMI(PSRLW)
REC_INTERP_MMI(PSRAW)

REC_INTERP_MMI(PADDW)
REC_INTERP_MMI(PADDH)
REC_INTERP_MMI(PADDB)
REC_INTERP_MMI(PADDSW)
REC_INTERP_MMI(PADDSH)
REC_INTERP_MMI(PADDSB)
REC_INTERP_MMI(PADDUW)
REC_INTERP_MMI(PADDUH)
REC_INTERP_MMI(PADDUB)
REC_INTERP_MMI(PSUBW)
REC_INTERP_MMI(PSUBH)
REC_INTERP_MMI(PSUBB)
REC_INTERP_MMI(PSUBSW)
REC_INTERP_MMI(PSUBSH)
REC_INTERP_MMI(PSUBSB)
REC_INTERP_MMI(PSUBUW)
REC_INTERP_MMI(PSUBUH)
REC_INTERP_MMI(PSUBUB)

REC_INTERP_MMI(PCGTW)
REC_INTERP_MMI(PMAXW)
REC_INTERP_MMI(PMAXH)
REC_INTERP_MMI(PCGTH)
REC_INTERP_MMI(PCGTB)
REC_INTERP_MMI(PEXTLW)
REC_INTERP_MMI(PEXTLH)
REC_INTERP_MMI(PEXTLB)
REC_INTERP_MMI(PEXT5)
REC_INTERP_MMI(PPACW)
REC_INTERP_MMI(PPACH)
REC_INTERP_MMI(PPACB)
REC_INTERP_MMI(PPAC5)

REC_INTERP_MMI(PABSW)
REC_INTERP_MMI(PABSH)
REC_INTERP_MMI(PCEQW)
REC_INTERP_MMI(PMINW)
REC_INTERP_MMI(PMINH)
REC_INTERP_MMI(PADSBH)
REC_INTERP_MMI(PCEQH)
REC_INTERP_MMI(PCEQB)
REC_INTERP_MMI(PEXTUW)
REC_INTERP_MMI(PEXTUH)
REC_INTERP_MMI(PEXTUB)
REC_INTERP_MMI(PSLLVW)
REC_INTERP_MMI(PSRLVW)

REC_INTERP_MMI(QFSRV)

REC_INTERP_MMI(PMADDH)
REC_INTERP_MMI(PHMADH)
REC_INTERP_MMI(PMSUBH)
REC_INTERP_MMI(PHMSBH)
REC_INTERP_MMI(PMULTH)
REC_INTERP_MMI(PMADDW)
REC_INTERP_MMI(PMSUBW)
REC_INTERP_MMI(PMFHI)
REC_INTERP_MMI(PMFLO)
REC_INTERP_MMI(PMULTW)
REC_INTERP_MMI(PMADDUW)
REC_INTERP_MMI(PMULTUW)
REC_INTERP_MMI(PDIVUW)
REC_INTERP_MMI(PDIVW)
REC_INTERP_MMI(PDIVBW)

REC_INTERP_MMI(PINTH)
REC_INTERP_MMI(PCPYLD)
REC_INTERP_MMI(PAND)
REC_INTERP_MMI(PXOR)
REC_INTERP_MMI(PEXEH)
REC_INTERP_MMI(PREVH)
REC_INTERP_MMI(PEXEW)
REC_INTERP_MMI(PROT3W)

REC_INTERP_MMI(PSRAVW)
REC_INTERP_MMI(PMTHI)
REC_INTERP_MMI(PMTLO)
REC_INTERP_MMI(PINTEH)
REC_INTERP_MMI(PCPYUD)
REC_INTERP_MMI(POR)
REC_INTERP_MMI(PNOR)
REC_INTERP_MMI(PEXCH)
REC_INTERP_MMI(PCPYH)
REC_INTERP_MMI(PEXCW)

} // namespace MMI

// ---- COP0 ----
namespace COP0 {

REC_INTERP_COP0(MFC0)
REC_INTERP_COP0(MTC0)
void recBC0F()  { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP0::BC0F);  pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
void recBC0T()  { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP0::BC0T);  pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
void recBC0FL() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP0::BC0FL); pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
void recBC0TL() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP0::BC0TL); pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
REC_INTERP_COP0(TLBR)
REC_INTERP_COP0(TLBWI)
REC_INTERP_COP0(TLBWR)
REC_INTERP_COP0(TLBP)
void recERET() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP0::ERET); g_branch = 2; g_cpuFlushedPC = true; }
REC_INTERP_COP0(EI)
REC_INTERP_COP0(DI)

} // namespace COP0

// ---- COP1 ----
namespace COP1 {

REC_INTERP_COP1(MFC1)
REC_INTERP_COP1(CFC1)
REC_INTERP_COP1(MTC1)
REC_INTERP_COP1(CTC1)
void recBC1F()  { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP1::BC1F);  pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
void recBC1T()  { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP1::BC1T);  pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
void recBC1FL() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP1::BC1FL); pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
void recBC1TL() { armCallInterpreter(R5900::Interpreter::OpcodeImpl::COP1::BC1TL); pc += 4; g_branch = 1; g_cpuFlushedPC = true; }
REC_INTERP_COP1(ADD_S)
REC_INTERP_COP1(ADDA_S)
REC_INTERP_COP1(SUB_S)
REC_INTERP_COP1(SUBA_S)
REC_INTERP_COP1(ABS_S)
REC_INTERP_COP1(MOV_S)
REC_INTERP_COP1(NEG_S)
REC_INTERP_COP1(MAX_S)
REC_INTERP_COP1(MIN_S)
REC_INTERP_COP1(MUL_S)
REC_INTERP_COP1(DIV_S)
REC_INTERP_COP1(SQRT_S)
REC_INTERP_COP1(RSQRT_S)
REC_INTERP_COP1(MULA_S)
REC_INTERP_COP1(MADD_S)
REC_INTERP_COP1(MSUB_S)
REC_INTERP_COP1(MADDA_S)
REC_INTERP_COP1(MSUBA_S)
REC_INTERP_COP1(C_F)
REC_INTERP_COP1(C_EQ)
REC_INTERP_COP1(C_LT)
REC_INTERP_COP1(C_LE)
REC_INTERP_COP1(CVT_S)
REC_INTERP_COP1(CVT_W)

} // namespace COP1

} // namespace OpcodeImpl
} // namespace Dynarec
} // namespace R5900
